application: unitconversionbot
version: v0-4-3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  upload: static/index.html
  static_files: static/index.html

- url: /index.html
  static_dir: static

- url: /api/.*
  script: app.app

skip_files:
  - ^\.git$
  - ^tests$
  - ^scripts$
  - ^stats$
  - .*\.pyc$
  - ^static/logo\.png$
  - ^static/logo\.pxm$
  - ^static/screenshot\.png$
  - ^\.gitignore$
  - ^devRequirements\.txt$
  - ^README\.md$
