# -*- coding: utf-8 -*-
import os
import sys
sys.path.append('.')

import requests
from config import OPENEXHANGERATES_API_KEY

unitsDir = os.path.join(os.path.dirname(__file__), '..', 'units')

currenciesTemplateFile = open(os.path.join(unitsDir, '__currenciesTemplate.py'), 'r')
currenciesTemplate = currenciesTemplateFile.read().decode('utf-8')

rawResponse = requests.get('https://openexchangerates.org/api/latest.json?app_id=' + OPENEXHANGERATES_API_KEY)
response = rawResponse.json()

for currencyName, exchangeRate in response['rates'].iteritems():
    replaceFrom = "{} = ([".format(currencyName)
    exchangeRateToBaseCurrency = float(exchangeRate)
    exchangeRateFromBaseCurrency = 1 / exchangeRateToBaseCurrency
    replaceTo = u'{} = ({}, ['.format(currencyName, exchangeRateFromBaseCurrency)
    currenciesTemplate = currenciesTemplate.replace(replaceFrom, replaceTo)

currenciesTemplate += """\n# DO NOT ALTER THIS FILE. IT IS DYNAMICALLY GENERATED BY ../updateCurrencies.py
# ALTER __currenciesTemplate.py
"""

currenciesTemplate = currenciesTemplate.encode('utf-8')

if currenciesTemplate.find('!') != -1:
    print currenciesTemplate
    sys.exit(1)

currenciesFile = open(os.path.join(unitsDir, 'currencies.py'), 'w')
currenciesFile.write(currenciesTemplate)
