# -*- coding: utf-8 -*-
USD = (1,      [u'$',    'US dollar', 'US dollars', 'American dollar', 'American dollars'])
EUR = (1.08570560007, [u'€',    'euro', 'euros'])
JPY = (0.00876501007976, [u'¥',    'yen', 'yens'])
GBP = (1.41500757029, [u'£',    'pound sterling', 'pounds sterling'])
CHF = (0.992358836955, [u'Fr',   'Swiss franc', 'Swiss francs', 'franc', 'francs', 'Fr.'])
CAD = (0.752728641325, [u'C$',   'Canadian dollar', 'Canadian dollars'])
RUB = (0.014203940173, [u'₽',    'Russian ruble', 'Russian rubles', 'ruble', 'rubles', 'rouble', 'roubles'])
CNY = (0.15337658553, [u'yuan', 'yuan', 'yuans'])


_BASE = USD
_CATEGORY = 'currencies'

# DO NOT ALTER THIS FILE. IT IS DYNAMICALLY GENERATED BY ../updateCurrencies.py
# ALTER __currenciesTemplate.py
