# -*- coding: utf-8 -*-
USD = (1,      [u'$',    'US dollar', 'US dollars', 'American dollar', 'American dollars'])
EUR = (0.91735, [u'€',    'euro', 'euros'])
JPY = (113.96, [u'¥',    'yen', 'yens'])
GBP = (0.71035, [u'£',    'pound sterling', 'pounds sterling'])
CHF = (0.9944, [u'Fr',   'Swiss franc', 'Swiss francs', 'franc', 'francs', 'Fr.'])
CAD = (1.3434, [u'C$',   'Canadian dollar', 'Canadian dollars'])
RUB = (73.465, [u'₽',    'Russian ruble', 'Russian rubles', 'ruble', 'rubles', 'rouble', 'roubles'])
CNY = (6.5405, [u'yuan', 'yuan', 'yuans'])


_BASE = USD
_TYPE = 'currency'

# DO NOT ALTER THIS FILE. IT IS DYNAMICALLY GENERATED BY ../updateCurrencies.py
# ALTER __currencyTemplate.py
