name: CI

on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install --user pipenv

      - name: Install dependencies
        run: pipenv install --dev

      - name: Lint
        run: pipenv run make lint

      - name: Test
        run: pipenv run make test
